// <auto-generated />
namespace MattBaines.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ACObjectImagePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ACObjectImagePath));
        
        string IMigrationMetadata.Id
        {
            get { return "201211101802181_ACObjectImagePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
